name: Django Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          ssh root@${{ secrets.DO_HOST }} << 'EOF'
          cd /path/to/your/django/project  # Change this
          git pull origin main  # Change branch if needed
          source /path/to/your/venv/bin/activate  # Activate virtualenv
          pip install -r requirements.txt  # Install new dependencies
          python manage.py migrate  # Apply migrations
          python manage.py collectstatic --noinput  # Collect static files
          systemctl restart gunicorn  # Restart Gunicorn
          systemctl restart nginx  # Restart Nginx if using it
          EOF
